language: php
php:
  - 7.3

cache:
  apt: true
  directories:
    - $HOME/.composer/cache

before_install:
  - phpenv config-rm xdebug.ini

before_script:
  - echo "extension = redis.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - composer self-update
  - composer install --prefer-source --no-interaction --dev
  - php vendor/bin/phpunit
